=== nachooosnchezz/JavaScript/Ejercicio Luigi y Nacho__eduardocorreccion/Tienda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" type="productoType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="productoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" minOccurs="1"/>
            <xs:element name="categoría" type="xs:string" minOccurs="1"/>
            <!-- CAMBIAR LA TILDE -->
            <xs:element name="precio" type="xs:decimal" minOccurs="1"/>
            <!-- añadir atributo en el xml que se llame "tipo-moneda" -->
            <xs:element name="disponibilidad" type="xs:boolean" minOccurs="1"/>
            <xs:element name="fabricante" type="xs:string" minOccurs="1"/>
            <xs:element name="especificaciones" type="especificacionesType" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="especificacionesType">
        <xs:sequence>
            <xs:element name="procesador" type="xs:string"/>
            <xs:element name="ram" type="xs:string"/>
            <xs:element name="almacenamiento" type="xs:string"/>
            <xs:element name="pantalla" type="xs:string"/>
            <xs:element name="sistema_operativo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== nachooosnchezz/JavaScript/Ejercicio Luigi y Nacho__eduardocorreccion/Tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- NO ESTABA BIEN LINKEADO -->
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Tienda.xsd">
    <producto>
        <nombre>RAM HyperX Fury Black DDR4</nombre>
        <categoria>Inform√°tica</categoria>
        <precio>45</precio>
        <disponibilidad tipo="true"></disponibilidad>
        <fabricante>HyperX</fabricante>
        <especificaciones>
            <procesador></procesador>
            <ram>8GB</ram>
            <almacenamiento></almacenamiento>
            <pantalla></pantalla>
            <sistema_operativo></sistema_operativo>
        </especificaciones>
    </producto>
</tienda>
