=== nachooosnchezz/JavaScript/POKEMON/index2.dtd
<!ELEMENT ligaPokemon (pokedex, entrenadores)>

    <!ELEMENT pokedex (pokemon+)>
        <!ELEMENT pokemon (nombre, imagen, especie, tipo+, habilidades, stats)>
            <!ELEMENT nombre (#PCDATA)>
                <!ATTLIST nombre id ID #REQUIRED>
            <!ELEMENT imagen (#PCDATA)>
            <!ELEMENT especie (#PCDATA)>
            <!ELEMENT tipo (#PCDATA)>
            <!ELEMENT habilidades (habilidad+, habilidadDestacada)>
                <!ELEMENT habilidad (#PCDATA)>
                <!ELEMENT habilidadDestacada (#PCDATA)>
            <!ELEMENT stats (PS, Ataque, Defensa, Velocidad, AtaqueEspecial, DefensaEspecial)>
                <!ELEMENT PS (#PCDATA)>
                <!ELEMENT Ataque (#PCDATA)>
                <!ELEMENT Defensa (#PCDATA)>
                <!ELEMENT Velocidad (#PCDATA)>
                <!ELEMENT AtaqueEspecial (#PCDATA)>
                <!ELEMENT DefensaEspecial (#PCDATA)>

    <!ELEMENT entrenadores (entrenador+)>
        <!ELEMENT entrenador (nombreEntrenador, apellidos, edad, fechaNacimiento, lugarNacimiento, pokemonEntrenador+)>
            <!ELEMENT nombreEntrenador (#PCDATA)>
            <!ELEMENT apellidos (#PCDATA)>
            <!ELEMENT edad (#PCDATA)>
            <!ELEMENT fechaNacimiento EMPTY>
                <!ATTLIST fechaNacimiento dia CDATA #REQUIRED>
                <!ATTLIST fechaNacimiento mes CDATA #REQUIRED>
                <!ATTLIST fechaNacimiento año CDATA #REQUIRED>
            <!ELEMENT lugarNacimiento (#PCDATA)>
            <!ELEMENT pokemonEntrenador (mote, genero, fechaCaptura, tipoPokeball)>
                <!ATTLIST pokemonEntrenador numeroPokedex IDREF #REQUIRED>
                <!ELEMENT mote (#PCDATA)>
                <!ELEMENT genero (#PCDATA)>
                <!ELEMENT fechaCaptura (#PCDATA)>
                    <!ATTLIST fechaCaptura dia CDATA #REQUIRED>
                    <!ATTLIST fechaCaptura mes CDATA #REQUIRED>
                    <!ATTLIST fechaCaptura año CDATA #REQUIRED>
                <!ELEMENT tipoPokeball (#PCDATA)>

=== nachooosnchezz/JavaScript/POKEMON/index2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<!DOCTYPE ligaPokemon SYSTEM "index2.dtd">

<ligaPokemon>
    <pokedex>
        <pokemon>
            <nombre id="P1">Bulbasaur</nombre>
            <imagen>Bulbasaur.jpg</imagen>
            <especie>Seed Pokémon</especie>
            <tipo>Planta</tipo>
            <tipo>Veneno</tipo>
            <habilidades>
                <habilidad>Espesura</habilidad>
                <habilidad>SobreCarga</habilidad>
                <habilidad>Clorofila</habilidad>
                <habilidad>Insomnio</habilidad>
                <habilidadDestacada>Retroceso</habilidadDestacada>
            </habilidades>
            <stats>
                <PS>45</PS>
                <Ataque>49</Ataque>
                <Defensa>49</Defensa>
                <Velocidad>45</Velocidad>
                <AtaqueEspecial>65</AtaqueEspecial>
                <DefensaEspecial>65</DefensaEspecial>
            </stats>
        </pokemon>
        <!-- Otros Pokémon de la primera generación aquí -->
    </pokedex>
    <entrenadores>
        <entrenador>
            <nombreEntrenador>Ash</nombreEntrenador>
            <apellidos>Ketchum</apellidos>
            <edad>10</edad>
            <fechaNacimiento dia="22" mes="septiembre" año="2014"/>
            <lugarNacimiento>Pueblo Paleta</lugarNacimiento>
            <pokemonEntrenador numeroPokedex="P1">
                <mote>Bulbasaur</mote>
                <genero>Masculino</genero>
                <fechaCaptura dia="1" mes="enero" año="2024"/>
                <tipoPokeball>UltraBall</tipoPokeball>
            </pokemonEntrenador>
            <!-- Otros Pokémon de Ash aquí -->
        </entrenador>
        <!-- Otros entrenadores aquí -->
    </entrenadores>
</ligaPokemon>
